# Generated by Django 4.2.7 on 2025-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='excludes',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='includes',
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
