"""
Django settings for turism project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u(1c!dytun*(n4xrm*pwyrbjs5y#52!bs^@ix^pea!$b%pi(96'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'django_filters',

    'tutu',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'turism.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'turism.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Классы аутентификации - JWT для API
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # Права доступа по умолчанию
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Чтение - всем, запись - авторизованным
    ),

    # Пагинация - разбиение на страницы
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 10 записей на страницу

    # Системы фильтрации
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # Фильтрация по полям
        'rest_framework.filters.SearchFilter',  # Поиск
        'rest_framework.filters.OrderingFilter',  # Сортировка
    ],

    # Автоматическая генерация схемы для Swagger
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ==================== JWT НАСТРОЙКИ ====================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Время жизни access токена - 1 час
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1)  # Время жизни refresh токена - 1 день
}

# ==================== CORS НАСТРОЙКИ ====================

# Разрешенные источники для межсайтовых запросов
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000"  # React development server (альтернативный)
]

# Разрешить передачу cookies и авторизационных данных
CORS_ALLOW_CREDENTIALS = True

# ==================== SWAGGER НАСТРОЙКИ ====================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Туристическое агентство - API',  # Заголовок документации
    'DESCRIPTION': 'API для бронирования туров и управления направлениями',  # Описание
    'VERSION': '1.0.0',  # Версия API
    'SERVE_INCLUDE_SCHEMA': False,  # Не включать полную схему в UI

    # Настройки Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,  # Сохранять авторизацию при перезагрузке
        'displayRequestDuration': True,  # Показывать время выполнения запросов
    },

    'COMPONENT_SPLIT_REQUEST': True,  # Разделять запросы на компоненты

    # Определение схемы безопасности для JWT
    'SECURITY': [
        {
            'Bearer': {
                'type': 'http',  # Тип схемы - HTTP
                'scheme': 'bearer',  # Схема - Bearer token
                'bearerFormat': 'JWT',  # Формат - JWT
            }
        }
    ],

    # Требования безопасности по умолчанию
    'SECURITY_REQUIREMENTS': [
        {
            'Bearer': []  # Для всех endpoints требуется JWT токен
        }
    ],
}

# Тип поля для автоматических первичных ключей
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'